master_driverUrl=jdbc:sqlserver://127.0.0.1:1433;database=mjdb;user=sa;password=lwc
master_username=sa
master_password=lwc

slave_driverUrl=jdbc:sqlserver://127.0.0.1:1433;database=midphoto;user=sa;password=lwc
slave_username=sa
slave_password=lwc